const DUMMY_PRICE_LIST = [
  {
    articleNo: "A-1001",
    productService: "Web Hosting Basic",
    inPrice: 5,
    price: 10,
    unit: "month",
    inStock: 120,
    description: "Basic shared hosting plan",
  },
  {
    articleNo: "A-1002",
    productService: "Web Hosting Pro",
    inPrice: 8,
    price: 18,
    unit: "month",
    inStock: 80,
    description: "Pro hosting with SSL",
  },
  {
    articleNo: "A-1003",
    productService: "Domain Registration",
    inPrice: 2.5,
    price: 5,
    unit: "year",
    inStock: 300,
    description: "Domain registration service",
  },
  {
    articleNo: "A-1004",
    productService: "Email Hosting",
    inPrice: 1.5,
    price: 4,
    unit: "month",
    inStock: 500,
    description: "Professional email hosting",
  },
  {
    articleNo: "A-1005",
    productService: "Website Maintenance",
    inPrice: 15,
    price: 30,
    unit: "hour",
    inStock: 999,
    description: "Website maintenance service",
  },
  {
    articleNo: "A-1006",
    productService: "Cloud Backup",
    inPrice: 3,
    price: 7,
    unit: "month",
    inStock: 400,
    description: "Automated cloud backup solution",
  },
  {
    articleNo: "A-1007",
    productService: "SSL Certificate",
    inPrice: 6,
    price: 12,
    unit: "year",
    inStock: 250,
    description: "Secure SSL certificate",
  },
  {
    articleNo: "A-1008",
    productService: "Dedicated Server",
    inPrice: 60,
    price: 120,
    unit: "month",
    inStock: 25,
    description: "High performance dedicated server",
  },
  {
    articleNo: "A-1009",
    productService: "VPS Hosting",
    inPrice: 20,
    price: 45,
    unit: "month",
    inStock: 75,
    description: "Virtual private server hosting",
  },
  {
    articleNo: "A-1010",
    productService: "Website Design",
    inPrice: 200,
    price: 500,
    unit: "project",
    inStock: 10,
    description: "Custom website design service",
  },
  {
    articleNo: "A-1011",
    productService: "SEO Optimization",
    inPrice: 50,
    price: 150,
    unit: "month",
    inStock: 60,
    description: "Search engine optimization service",
  },
  {
    articleNo: "A-1012",
    productService: "Content Writing",
    inPrice: 10,
    price: 25,
    unit: "article",
    inStock: 300,
    description: "Professional content writing",
  },
  {
    articleNo: "A-1013",
    productService: "Email Marketing",
    inPrice: 15,
    price: 35,
    unit: "campaign",
    inStock: 90,
    description: "Targeted email marketing campaign",
  },
  {
    articleNo: "A-1014",
    productService: "Social Media Management",
    inPrice: 40,
    price: 90,
    unit: "month",
    inStock: 50,
    description: "Social media account management",
  },
  {
    articleNo: "A-1015",
    productService: "Analytics Setup",
    inPrice: 20,
    price: 60,
    unit: "project",
    inStock: 40,
    description: "Analytics and tracking setup",
  },
  {
    articleNo: "A-1016",
    productService: "Mobile App Maintenance",
    inPrice: 30,
    price: 75,
    unit: "month",
    inStock: 70,
    description: "Ongoing mobile app maintenance",
  },
  {
    articleNo: "A-1017",
    productService: "API Integration",
    inPrice: 25,
    price: 70,
    unit: "project",
    inStock: 35,
    description: "Third-party API integration",
  },
  {
    articleNo: "A-1018",
    productService: "Security Audit",
    inPrice: 100,
    price: 250,
    unit: "audit",
    inStock: 15,
    description: "Full security audit service",
  },
  {
    articleNo: "A-1019",
    productService: "Performance Optimization",
    inPrice: 45,
    price: 110,
    unit: "project",
    inStock: 20,
    description: "Website performance optimization",
  },
  {
    articleNo: "A-1020",
    productService: "Technical Support",
    inPrice: 5,
    price: 15,
    unit: "hour",
    inStock: 1000,
    description: "24/7 technical support",
  },
];

export default DUMMY_PRICE_LIST;
